# Generated by Django 3.2.5 on 2021-08-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=256)),
                ('trees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RewildPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('rewild', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenleaf.rewild')),
            ],
        ),
    ]
