# Generated by Django 3.2.6 on 2021-08-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenleaf', '0002_alter_rewildphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewild',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
