# Generated by Django 3.2.6 on 2021-08-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenleaf', '0003_rewild_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewild',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
